### ISSUE TITLE
Problems with making multisortable when li is dynamically added

### ISSUE THREAD

**Issue by deopard** [shvetsgroup/jquery.multisortable#3] opened 2012-06-24 14:12 UTC
Hi I am loving your plugin and I am trying to use it in my small project.
I saw that the log 0.1.3 where making empty ul multisortable problem is fixed but when I tried it..
It seems like it still doesn't work.
I have an empty ul and made it multisortable.
And then I dynamically added li by using jquery's append function.
so the ul has some li s but they can't be clicked.

I looked up the source and found that it binds function to the click event  when it is made multisortable..

Am i using it wrong? Or does the souce has a bug?

Thank you.

**Comment by iamvery** [comment] 2012-06-28 03:55
Hey man, sorry its taken me awhile to get back to you. As you can see, I haven't really actively maintained this project. After originally importing it and getting it where I needed for myself, it went dormant. Call this particular behavior "bug", but here's a possible solution:

I believe the problem is that the new items added to the list are not "multiselectable", so you should be able to do something like:

```
$('ul#your_dynamic_list li').multiselectable() // supply any custom settings, like the "selectedClass"
```

Try that out and see what happens... Seemed to work for me.

**Comment by iamvery** [comment] 2013-09-16 21:47
Closing for lack of communication.

**Closed as completed by iamvery** 2013-09-16 21:47 UTC
Labels: bug
